package main

import (
	"testing"
)

// TestSum does what it says
func TestSum(t *testing.T) {
	t.Error("I failed")
}
